---
driver:
  name: docker
#  use_sudo: false

provisioner:
  name: chef_zero

platforms:
#  - name: ubuntu-14.04
  - name: centos-7.2

suites:
  - name: default
    run_list:
      - recipe[apache::default]
    attributes:

#  - name: centos-7.2
#    run_list:
#      - recipe[apache::default]
#    attributes:

